---
extends:
  - standard
  - import/warnings
plugins:
  - no-class
  - import
env:
  es6: true

rules:
  semi:
    - 2
    - always
  no-extra-semi: 2
  semi-spacing:
    - 2
    -
      before: false
      after: true

  arrow-parens:
    - 1
    - as-needed

globals:
  zone: false
