---
extends:
  - semistandard
  - import/warnings
plugins:
#  - lodash3
  - no-class
  - prototype-chain
  - import
parser: babel-eslint

rules:
  space-before-function-paren: 0
  arrow-parens:
    - 1
    - as-needed

  # plugins follow
  prototype-chain/prototype-chain:
    - 1
    - 2
    - 2
globals:
  zone: false
